### ISSUE TITLE
[create-snowpack-app] Windows not respecting `chalk.dim`

### ISSUE THREAD

**Issue by stramel** [pikapkg/create-snowpack-app#108]
Windows isn't respecting the `chalk.dim` characters resulting in very hard to read output.

https://github.com/pikapkg/create-snowpack-app/blob/4a392780ad7c6bd6c5d021e032e89f18c01053e1/packages/create-snowpack-app/index.js#L176-L184

results in 

![image](https://user-images.githubusercontent.com/855184/83545410-c55d6900-a4c4-11ea-9ed6-48905d362ede.png)

I'm not sure if we should just do some indentation or change the format to `<command> dim(- <description>)`. I'm leaning towards the latter

**Comment by FredKSchott** [comment]
In previous output we also use `-` to indicate a new line, so something like:

```
  - yarn install
    Install all dependencies.

  - yarn start
    Start your dev server.
```

Although I think I like keeping it all on the same line better as well:

```
  yarn start          Start your dev server.
  yarn build          Build your website.
  yarn test           Run your tests.
```

**Comment by stramel** [comment]
Want me to throw together a quick PR or do you want to just do it quickly?

**Comment by FredKSchott** [comment]
Would love a PR if you can! I just stepped away from my laptop but can do it tonight as well otherwise
