### ISSUE TITLE
@snowpack/app-template-react-typescript build broken

### ISSUE THREAD

**Issue by aaronshaf** [pikapkg/create-snowpack-app#117]
Steps to reproduce:

```bash
npx create-snowpack-app my_app --template @snowpack/app-template-react-typescript
cd my_app
npm run build
serve -s build
```

Browser console:

```
Uncaught TypeError: React.createElement is not a function
    at index.js:8
```

**Comment by wiesson** [comment]
I also experienced that bug. It looks like `import * as React from '...'` is not processed correctly to `import React from '...'`

**Comment by ryands17** [comment]
`import * as React` build perfectly on `@snowpack/app-scripts-react` version `1.1.0`. I think the new version specifically might be causing this issue.

**Comment by FredKSchott** [comment]
Sorry about that, it should be `import React from 'react'` in the official template, but we also should support this in Snowpack. Fixed in https://github.com/pikapkg/snowpack/commit/72933b3dc1e6cead15a950ce2353ae563acec775
