### ISSUE TITLE
Adding Tailwind React template 

### ISSUE THREAD

**Issue by mrkldshv** [pikapkg/create-snowpack-app#128]
I would be glad to make React and Preact community templates with Tailwind built-in so people can just bootstrap it without configuring. It is really easy to make but I think it might be a good idea to add them.

**Comment by FredKSchott** [comment]
Yes! That would be amazing

**Comment by mrkldshv** [comment]
Should I simply publish it as npm package and then include it in the readme as a community plugin?

**Comment by FredKSchott** [comment]
Yes please!

**Comment by mrkldshv** [comment]
@FredKSchott Is it reasonable to make snowpack-preact-template? The configuration will be pretty much similar to existing [react template](https://github.com/mrkldshv/snowpack-react-tailwind). So I'm not sure about this one.

**Comment by FredKSchott** [comment]
I think the react + tailwind template is probably enough to show people how it's done. I'd be fine with adding a note in the README saying "React/Preact + Tailwind" instead, if you added a note in your README with instructions for how to replace React with Preact.

**Comment by mrkldshv** [comment]
Awesome, I will do like that.
