### ISSUE TITLE
homepage vs buildOptions.baseUrl

### ISSUE THREAD

**Issue by danprince** [pikapkg/create-snowpack-app#131]
At the moment you need to use a combo of `config.buildOptions.baseUrl` and `config.homepage` to bundle a project correctly.

`buildOptions.baseUrl` is needed for `snowpack` and `homepage` is needed for the bundler plugins. Should these options be unified?

https://github.com/pikapkg/create-snowpack-app/blob/4ca630a9b348ef07e1b83adfb342eda32bcff3eb/packages/plugin-parcel/plugin.js#L72-L74

https://github.com/pikapkg/create-snowpack-app/blob/4ca630a9b348ef07e1b83adfb342eda32bcff3eb/packages/plugin-webpack/plugin.js#L45

I think the webpack plugin should also be using the [`publicPath`](https://webpack.js.org/guides/public-path/) configuration option, as well.

**Comment by FredKSchott** [comment]
Yes! the plugins are out of date, they should be updated to use `config.buidOptions.baseUrl` which is the new, documented config option for this

**Comment by FredKSchott** [comment]
Fixed in #134 & released
