### ISSUE TITLE
svelte template source map not working for .svelte file

### ISSUE THREAD

**Issue by wighawag** [pikapkg/create-snowpack-app#14]
Hi, just tried the svelte template and the .svelte file do not have source map enabled. Any options to enable that ?
Note that the other .js file in src worls fine (since they are not transformed)

**Comment by FredKSchott** [comment]
Hey there, right now Snowpack doesn't support source maps (although support is planned). 

Since each file is processed & shipped to the browser individually, each file should be easier to navigate & debug without additional source maps.
