### ISSUE TITLE
Out-of-the-Box PWA Support for app-template-preact

### ISSUE THREAD

**Issue by DamianRivas** [pikapkg/create-snowpack-app#143]
Would it be possible to add out-of-the-box PWA support for the preact template just like in [preact-cli](https://github.com/preactjs/preact-cli)?

**Comment by FredKSchott** [comment]
What would this entail / what's missing from the current template?

**Comment by DamianRivas** [comment]
I'm not entirely sure what preact-cli does besides provide the necessary files like a `manifest.json`, service worker, and icons. IIRC it also uses different service workers for debugging and the production build. So I'd say that's a good starting point. Beyond that I'm not sure what else they do if anything.

Google has a page showcasing the bare minimum needed to make a web app installable: https://web.dev/codelab-make-installable/

**Comment by FredKSchott** [comment]
To be honest, the best thing for this might be just a blog post titled: "Building a PWA with Snowpack" that documented how to go from the CSA Preact app -> a full PWA. That would be super valuable. 

If someone wrote that, I'd love to promote it and link to it in the docs!
