### ISSUE TITLE
Provide a blank template for Typescript

### ISSUE THREAD

**Issue by mushtaq** [pikapkg/create-snowpack-app#157]
There is no Typescript equivalent of `app-template-blank`. 

It will be nice to have `app-template-blank-typescript` with default recommended values in `tsconfig.json`.

**Comment by stramel** [comment]
I think I can manage to put something like this together

**Comment by David-Else** [comment]
You can create a default `tsconfig.json` with `tsc --init`. I find it very conservative and would definitely make the following changes:
```json
"target": "es5", CHANGE TO "ES2020"
"module": "commonjs" CHANGE TO ""ESNext"
```
Add the following by uncommenting them:
```
"moduleResolution": "node",
"sourceMap": true,
```

**Comment by FredKSchott** [comment]
@stramel that would be great!

**Comment by stramel** [comment]
I started on this while I was traveling through the airport but haven't gotten around to cleaning it up and putting out a PR. Hope to have something out tomorrow
