### ISSUE TITLE
Feature request: Add pnpm as install option

### ISSUE THREAD

**Issue by David-Else** [pikapkg/create-snowpack-app#159]
I see there is a `--use-yarn` option, would be great to add `--use-pnpm`!

https://pnpm.js.org/

**Comment by FredKSchott** [comment]
+1! Would love to see this added if anyone is willing to tackle!

**Comment by stramel** [comment]
@FredKSchott Are you thinking that we would offer a `--use-pnpm` option? Or do you have thoughts on something like `--skip-install` or `--use-installler=pnpm`/`--use-installer=yarn`?

**Comment by David-Else** [comment]
@FredKSchott I had a quick look at https://github.com/pikapkg/create-snowpack-app/blob/master/packages/create-snowpack-app/index.js and I would love to have a go, I am new to Node.js but it doesn't look too confusing.

Could you quickly confirm there are no other files involved and it is just a case of modifying the logic here? I would change those ternaries to switches, does that sound about right?

**Comment by FredKSchott** [comment]
I'd prefer `--use-pnpm` for now, but that doesn't mean we couldn't represent this in the code as `installer = 'npm' | 'yarn' | 'pnpm'`. 

@David-Else thanks for offering to tackle! Yup, it should only affect the output and how you run the first install in the project. Also, the README should be updated to mention this

**Comment by David-Else** [comment]
@FredKSchott Cool, I will do it. You can mark this issue assigned if you like, I am not sure how you do things around here.
