### ISSUE TITLE
@snowpack/app-template-blank-typescript does not exist on NPM

### ISSUE THREAD

**Issue by princemaple** [pikapkg/create-snowpack-app#169]

**Comment by stramel** [comment]
It hasn't been published yet.

**Comment by stramel** [comment]
Sorry for the brevity of my previous comment, I was on my way to bed when I saw this and wanted to reply quickly. 

@FredKSchott @drwpow Can one of you release the new template? I don't believe I have access to do so.

**Comment by princemaple** [comment]
No worries at all. I happened to want to give snowpack a go today and thought this was well established. Didn't even think about the possibility that this was new. :)

**Comment by drwpow** [comment]
Oh yes! I can release right now. Sorry—I should have released right when that template was merged and it slipped my mind 😅 . Feel free to always ping me when there’s something that should be released.

**Comment by drwpow** [comment]
Released!
