### ISSUE TITLE
plugin-dotenv doesn't work

### ISSUE THREAD

**Issue by HassanAlgoz** [pikapkg/create-snowpack-app#172]
1. I installed it with `npm install --save-dev @snowpack/plugin-dotenv`.
2. Added the plugin in `snowpack.config.json`:
```json
"plugins": ["@snowpack/plugin-dotenv"]
```
3. Added a .env file with key value pairs:
```env
key1=val1
key2=val2
```

Yet I don't see anything added to `import.meta.env`. Am I missing something?

snowpack version: 2.6.4

**Comment by ruslanchek** [comment]
Same here. I think the plugin has a lack of documentation. Trying to get it works.

**Comment by stramel** [comment]
Correct, the environment variables need to be prefixed with `SNOWPACK_PUBLIC_` to be used by Snowpack. This is to prevent accidental exposure of keys/secrets. I will update the README to include this note. Sorry for the confusion.
