### ISSUE TITLE
react-typescript template build errors

### ISSUE THREAD

**Issue by iBaldie** [pikapkg/create-snowpack-app#22]
`npx create-snowpack-app snowpack-react-ts --template @snowpack/app-template-react-typescript`

`cd snowpack-react-ts/`

`npm run build`

![Screenshot 2020-05-06 at 21 48 49](https://user-images.githubusercontent.com/3380651/81227207-f17bec00-8fe3-11ea-94ac-b0d87a6dbc5f.png)

**Comment by FredKSchott** [comment]
Oh my god i can't believe we missed this! Truly embarrassing. 
Pushing a fix now, updating @snowpack/app-scripts should get you the fix

**Comment by iBaldie** [comment]
Easy done 😊 Assume it was a compile of type was set wrong for css?

**Comment by FredKSchott** [comment]
no it was even worse, the template broke when you added TS syntax 🤦

**Comment by iBaldie** [comment]
@FredKSchott I am still getting this error... 😕 

<img width="965" alt="Screenshot 2020-05-07 at 08 17 32" src="https://user-images.githubusercontent.com/3380651/81265553-35e6a680-903b-11ea-9323-4ee331ce4c56.png">

I updated to 0.3.0 and updated snowpack to 2.0.0-beta.9
