### ISSUE TITLE
Typescript conflict with required file extension

### ISSUE THREAD

**Issue by MrColdfinger** [pikapkg/create-snowpack-app#24]
When running `snowpack build` on a project using typescript, error messages are shown "...missing required file extension" if I use imports without `.ts` extension. The build output will also error if loaded on a browser.

The reason why omitting extensions when using typescript is desirable is because of this long-standing [issue](https://github.com/microsoft/TypeScript/issues/27481).

The good news is running `snowpack build --bundle` works and produces a functioning output. Just wondering if anyone has a found a solution / compromise for this?

**Comment by FredKSchott** [comment]
This was actually just fixed this morning (in 834f620) mind updating and trying again?

**Comment by FredKSchott** [comment]
closing because i think its been resolved, but obviously lmk if it still persists
