### ISSUE TITLE
Svelte template - 'cat' is not recognized

### ISSUE THREAD

**Issue by countnazgul** [pikapkg/create-snowpack-app#27]
npx/npm 6.14.4
node v12.16.3

I'm trying the Svelte template under Windows (not using WSL). 
The installation is completing without an issue
`npx  create-snowpack-app myfolder --template @snowpack/app-template-svelte`

`npm start` although is producing an error while building:

```
  Server started in 14ms.

  mount:web_modules.......[DONE]
  mount:public............[DONE]
  plugin:svelte...........[READY]
  build:js................[RUNNING]

▼ Console

  [error] F:\dev\myfolder\src\index.js Error: Command failed with ENOENT: cat
  spawn cat ENOENT
  'cat' is not recognized as an internal or external command,
  operable program or batch file.
      at notFoundError (F:\DEV\myfolder\node_modules\snowpack\node_modules\cross-spawn\lib\enoent.js:6:26)
      at verifyENOENT (F:\DEV\myfolder\node_modules\snowpack\node_modules\cross-spawn\lib\enoent.js:40:16)
      at ChildProcess.cp.emit (F:\DEV\myfolder\node_modules\snowpack\node_modules\cross-spawn\lib\enoent.js:27:25)
...
``

**Comment by ervwalter** [comment]
I noticed the same.  It's because the snowpack.config.js in @snowpack/app-scripts-svelte specifies a build script for .js files that looks like:

```
"build:js": "cat"
```

But there is no `cat` executable on windows.  My workaround was to run npm start and/or npm build from a Git Bash prompt instead of from the Windows command prompt because Git Bash adds basic unix tools like `cat` to the path.

Maybe the template should install and use the [cat npm module](https://www.npmjs.com/package/cat) since that appears to be cross platform.

**Comment by ervwalter** [comment]
FYI, I did `npm install cat` in my sample project made from the template and it started working because that npm module installs a `cat` command in node_modules.

**Comment by FredKSchott** [comment]
Didn't even think of this! Could be smart to just add this as a dependency to the app-scripts package by default

**Comment by FredKSchott** [comment]
Update: With the way we're going, `cat` may just end up being the default behavior: If no build script is defined, assume it's okay to just copy over. In that case, we could just remove `cat` and solve this problem by ignoring it (for now, anyway)

**Comment by FredKSchott** [comment]
Fixed: files without a build script are now copied by default. This has been true for a while, but we are now also handling JS imports properly as well for JS files, with or without a 'build:js' script.

you can remove 'cat' from your build scripts (we're removing them now from the CSA apps) and this should solve this problem. 

if you run into this problem later on in your own scripts, you can check out: https://github.com/shelljs/shx

**Comment by countnazgul** [comment]
Thank you very much guys!
