### ISSUE TITLE
Blank template does not load CSS

### ISSUE THREAD

**Issue by agneym** [pikapkg/create-snowpack-app#28]
Blank template has a file `App.css` in `public` folder, but it isn't linked anywhere. 

 In earlier versions, the `.css` file in `src` folder was automatically transpiled and moved to `dist` folder with `build:css` if any. But that is no longer the case.

**Comment by FredKSchott** [comment]
Thank you! Just fixed. I ended up doing something more traditional (CSS loaded via HTML), lmk if you think it would be more useful just matching the format of the others (with CSS loaded via JS)
