### ISSUE TITLE
"ver is not defined" error on creation of template

### ISSUE THREAD

**Issue by Buuntu** [pikapkg/create-snowpack-app#31]
When running after installing snowpack@next (tried with snowpack as well), I get:
```
ver is not defined
```

I tried installing locally and globally.

Example run:
```bash
npx create-snowpack-app snowpack --template @snowpack/app-template-react-typescript
```

Node version: 14.2.0
Npm/npx version: 6.14.4
Running OS X Catalina

**Comment by ribizli** [comment]
so is `v0.3.4` unusable, use `v0.3.0` instead:
`npx -p create-snowpack-app@0.3.0 create-snowpack-app ...`

**Comment by Buuntu** [comment]
@ribizli that fixed it, thanks!

**Comment by FredKSchott** [comment]
Sorry about that everyone! This has been fixed in v0.3.5

**Comment by Buuntu** [comment]
@ribizli I don't know if this is relevant, but I now get:
```bash
$ npx snowpack dev

Error: Cannot find module '@snowpack/app-scripts-react'
Require stack:
- /Code/snowpack/node_modules/snowpack/dist-node/index.js
...
```

**Comment by FredKSchott** [comment]
hm, I see "@snowpack/app-scripts-react" successfully defined as a dependency in both react templates. Maybe retry in a fresh directory, or clear your npm cache? (`npm cache clear --force`)
