### ISSUE TITLE
Generated ReadMe claims that `npm run start` would run on port 3000, but it's actually port 8080

### ISSUE THREAD

**Issue by danieldiekmeier** [pikapkg/create-snowpack-app#37]
The README.md generated by `@snowpack/app-template-react-typescript` claims that `npm run start` would start the development server on `localhost:3000`, but when you actually run `npm run dev`,  it will open `localhost:8080` (!) in your default browser.

I only saw this in `@snowpack/app-template-react-typescript` and did not check is this also happens in the other packages.

**Comment by FredKSchott** [comment]
Fixed in 3eba394! Appreciate the ping
