### ISSUE TITLE
Build step missing after new setup

### ISSUE THREAD

**Issue by seriousManual** [pikapkg/create-snowpack-app#47]
When setting up a new app with svelte the build step does not complete (?), the "build:js" step is missing. When opening the app in the browser the dev server answers with 404.

![image](https://user-images.githubusercontent.com/1330022/81646323-52178880-942b-11ea-8b83-fa46edb2d0b9.png)

Steps to reproduce:

1. Run `npx create-snowpack-app new-dir --template @snowpack/app-template-svelte`
2. `cd new-dir`
3. `sp dev`

Node: 14.2
Snowpack: 2.0.0-beta.9

I am able to start a CSA app I created earlier (last weekish) just fine, the new created one does not work.

**Comment by FredKSchott** [comment]
Hmm, that version of Snowpack is a little out of date, mind updating and starting again with a fresh CSA install?

**Comment by seriousManual** [comment]
I upgraded to the latest version as of now (beta.19), now it works!

**Comment by seriousManual** [comment]
Just a FYI: 
I opened the (not working) project I created yesterday, when I start it with beta.19 it too does not work (answers with 404).

**Comment by FredKSchott** [comment]
It was working last night but now it's not working this morning? Very strange. Hard to say what's going on there, if it's a fresh install of the template then I can't reproduce.
