### ISSUE TITLE
Svelte components are built in dev mode

### ISSUE THREAD

**Issue by jamesopstad** [pikapkg/create-snowpack-app#59]
Running `npm run build` creates svelte components in dev mode. This seems to be correctly implemented in `plugin-svelte` so the plugin must not receive the correct environment variable.

**Comment by FredKSchott** [comment]
Great catch, thanks for filing. 

Fixed in https://github.com/pikapkg/snowpack/commit/08e898625ef30bca4a5a589e2973b6fd33d3fd49
