### ISSUE TITLE
Svelte hmr: dynamic imports yield a full page reload

### ISSUE THREAD

**Issue by germanftorres** [pikapkg/create-snowpack-app#70]
Hi,

Trying to understand and take advantage of svelte hmr. Really don't know if is just enough to include the hmr snippet in index.js, or if there's additional setup required on a per component basis in order to take full advantage of it.

The index.js is configured with the hmr code:
```
import App from "./App.svelte";
...

// Hot Module Replacement (HMR) - Remove this snippet to remove HMR.
// Learn more: https://www.snowpack.dev/#hot-module-replacement
if (import.meta.hot) {
  import.meta.hot.accept();
  import.meta.hot.dispose(() => {
    app.$destroy();
  });
}
```

My svelte app is using a client side router (Navaid) with dynamic imports and works great with snowpack.
```javascript
  //App.js

  // home component statically imported
  import index from './routes/index.svelte';


  router = Navaid('/')
    // home route in same bundle as App.js
    .on('/', () => run(Promise.resolve(index)))
    // other routes dynamically imported
    .on('/about', () => run(import('./routes/about.svelte')))
    .on('/sign-up', () => run(import('./routes/sign-up/index.svelte')))
    .on('/play/:band', params => run(import('./routes/play/index.svelte'), params))
    .listen();
```

If I change the statically imported `index.svelte` component, the hmr module signals an update of `_dist_/index.js` which in turn reloads the statically imported component chain.

If I change the dynamically imported components, the hmr module signals a full page reload. Maybe more hmr configuration code is required to make dynamically imported components to update instead of a full reload.

Thanks!!

**Comment by FredKSchott** [comment]
Thanks for filing! Looks like we'd skipped implementing dynamic imports for HMR, just added: https://github.com/pikapkg/snowpack/commit/23c574d2e9594fab9210998aa488a14dafb09281

Re-run with `2.0.0-rc.13` (I'll publish it in a little bit) and it should work as expected
