### ISSUE TITLE
[plugin-webpack] Support multi-entrypoint bundling

### ISSUE THREAD

**Issue by FredKSchott** [pikapkg/create-snowpack-app#74]
**Original Discussion:** https://www.pika.dev/npm/snowpack/discuss/232
/cc @yuheiy

Currently, @snowpack/plugin-webpack only works on SPAs, and assumes a single HTML file entrypoint. This wasn't a technical limitation, and our current code could be modified to run across every HTML file in your application.

**Comment by yuheiy** [comment]
What is the execution order of `run:*` and `bundle:*`? This relationship does not seem to be documented.

**Comment by yuheiy** [comment]
If `bundle:*` is executed after `run:*` ends, I feel like this plugin would work correctly. After the end of `run:*`, it should be able to read the fallback file.

https://github.com/pikapkg/create-snowpack-app/blob/6f4e11d3a355c8d72fd80db0483d9faa2d041171/packages/plugin-webpack/plugin.js#L76

**Comment by FredKSchott** [comment]
We should document that ordering. Currently, all "run" scripts will complete before the "bundle" script/plugin is run.

**Comment by FredKSchott** [comment]
But again, the issue described in OP is that fallback is not required / may not exist in your project if its not an SPA. The plugin should multiple entrypoints instead `/product.html`, `about.html`, etc.

**Comment by yuheiy** [comment]
Oh, I'm sorry. I misunderstood. In order to target the files generated by A I needed the following settings.

`snowpack.config.js`:

```diff
{
  "scripts": {
    "mount:_site": "mount _output --to /",
    "mount:src": "mount src --to /_dist_",
    "run:11ty": "eleventy",
    "run:11ty::watch": "$1 --watch"
  },
  "plugins": ["@snowpack/plugin-webpack"],
+ "devOptions": {
+   "fallback": "../_output/index.html"
+ }
}
```

**Comment by yuheiy** [comment]
It looks like we need to modify snowpack module to allow multiple values for the `fallback` property. Perhaps, like making the default value from `index.html` to `['index.html']`.

**Comment by FredKSchott** [comment]
Id rather just add support for the webpack plugin to search for all HTML files in your build directory, and then use those as entrypoints. Right now we're being lazy by just reading from fallback, but that's not really the right use of that config value.

**Comment by FredKSchott** [comment]
Tackled via #144, released in 1.3.0

**Comment by dickeylth** [comment]
Should the readme: https://github.com/pikapkg/create-snowpack-app/tree/master/packages/plugin-webpack#limitations be updated? I guess just add multiple entries to webpack configuration should work?

**Comment by FredKSchott** [comment]
Bah, my bad, I read the issue title wrong. We now support multiple entrypoints in the HTML file, but not multiple HTML files.

Would still love some help on this one!

**Comment by mxmul** [comment]
@FredKSchott I'm also trying to use this plugin with 11ty, and would love to see support for multiple HTML entries. I'd be happy to pick this up myself.
