### ISSUE TITLE
Snowpack + Fastify & General Questions

### ISSUE THREAD

**Issue by acg-thp** [pikapkg/create-snowpack-app#78]
Ideas on combining the two together as a template/starter project?

Also can snowpack take any npm package and pack it for client side use or only specific ones

**Comment by FredKSchott** [comment]
snowpack is meant to work with any npm package that currently works with Webpack, Rollup, Parcel, etc. Some npm packages rely on Node-only things that can't work in the browser (ex: `fs`) but for the most part snowpack works with everything you'd want it to.

**Comment by FredKSchott** [comment]
+1 on linking to a community template in the README for Snowpack + Fastify!
