### ISSUE TITLE
[error] [404] /web_modules/svelte/internal.js

### ISSUE THREAD

**Issue by mphuie** [pikapkg/create-snowpack-app#79]
Follow the instructions from the official site.  After running `npm start`, i get-

  [error] [404] /web_modules/svelte/internal.js
    ✘ <project_dir>/node_modules/.cache/snowpack/dev/svelte/internal.js

I've verified that the file exists in 

`node_modules/.cache/snowpack/dev/svelte/internal.js`

**Comment by FredKSchott** [comment]
Yup, sorry about that. Fixed in v2.0.2 that just went out!
