### ISSUE TITLE
Will ESLint be included as standard?

### ISSUE THREAD

**Issue by doutori** [pikapkg/create-snowpack-app#80]
Hi, snowpack team.
It's a great project. I love snowpack! 👍 

I think ESLint is a JavaScript standard Lint tool,
so I hope ESLint is included in these boilerplates.

**Comment by FredKSchott** [comment]
I love ESLint, but want to keep these CSA templates small.

We should definitely add a recipe for ESLint to snowpack.dev. This is as far as I got:

```
  "scripts": {
    "run:eslint": "eslint 'src/**.{js,jsx,ts,tsx}'",
  },
```

That runs ESLint once during dev & build. I had trouble getting eslint-watch to work, to add watching during development.

**Comment by ryands17** [comment]
@FredKSchott I have created a repo [here](https://github.com/ryands17/react-experimental) with eslint build and watch, and I could add it to CSA templates as well :)

**Comment by FredKSchott** [comment]
That would be great! feel free to create a PR against the README to add. a template is just an npm package containing all the files that you'd want in your template (basically, the entire repo)
