### ISSUE TITLE
out of the box react-typescript template build script throws a "$RefreshSig$ is not defined" browser error

### ISSUE THREAD

**Issue by canercandan** [pikapkg/create-snowpack-app#86]
1. ```npx create-snowpack-app new-dir --template @snowpack/app-template-react-typescript --use-yarn```

2. ```yarn build```

3. ```serve ./build```

4. Open the built bundle in the browser and it throws the following error (with no rendering):

```
Uncaught ReferenceError: $RefreshSig$ is not defined
```

Same happens by adding the webpack plugin + adding this in the config file:

```
{
  "extends": "@snowpack/app-scripts-react",
  "scripts": {
    "bundle:*": "@snowpack/plugin-webpack"
  },
  "plugins": [
    "@snowpack/plugin-webpack"
  ]
}
```

Any idea why this is happening?

Thanks

**Comment by FredKSchott** [comment]
That's very strange, I can't reproduce. My best guess is that your npm cache is corrupt, and you're actually using an old version of Snowpack (maybe?) You can run `npm cache clear --force` to confirm.

**Comment by sbauch** [comment]
I'm facing the same issue. sometimes it gets thrown from an imported module
```
var _s = $RefreshSig$();
```

other times, or if i remove the improt of that mofule, it gets thrown from the index.js, when calling `createSignatureFunctionForTransform`

```
/** React Refresh: Setup **/
if (import.meta.hot) {
  var prevRefreshReg = window.$RefreshReg$;
  var prevRefreshSig = window.$RefreshSig$;
  window.$RefreshReg$ = (type, id) => {
    window.$RefreshRuntime$.register(type, "/_dist_/pages/enterpriseAccount/index.js" + " " + id);
  }
  window.$RefreshSig$ = window.$RefreshRuntime$.createSignatureFunctionForTransform;
}
```

I'm on snowpack 2.0.3, using yarn. I had added a build script for processing some LESS, but removed that and still having issues, so like the OP its a vanilla CSA setup for react / typescript.

It also feels intermittent / hard to debug. I've been trying `yarn cache clean`, `snowpack install --reload`, blowing up the `web_modules` dir - none reliably fix things.

Like I just came back here to finish my post when snowpack started acting up again. I tried my debug things, nothing helped, then I finished my post here, and went back to my app and it loaded fine.

Hope this is at least somewhat helpful, happy to help further debug. snowpack has been wonderful so far when it works, but with this issue popping up throughout the day it makes it challenging to keep using.

**Comment by FredKSchott** [comment]
Yup, appreciate the feedback. We're getting a ton of new users from the v2 launch, which is amazing but means that we're suddenly running on peoples machines/usecases that we've never seen before. Appreciate the patience while we sort out the bugs :)

When you said out of the box, I assumed the blank template, but then that log that you shared looks like you've added some pages of your own. That could explain why I couldn't reproduce.

I've been reading more about how Create React App handles React Fast-Refresh support and they're under the impression that it's not yet ready for prime time. I may recommend that we follow suit, and move it behind an opt-in flag. Normal HMR is still plenty fast.

**Comment by sbauch** [comment]
totally understand it's early days here, am happy to be patient and help however I can!

I did add some of my own pages yup, sorry, by vanilla i meant that I am not using any other build scripts beyond what this CSA template provides

opt-in flag sgtm - I also had tried commenting out the HMR bits in index.tsx but that didn't seem to impact this, which I thought it might?

**Comment by FredKSchott** [comment]
A default CSA plugin is one that adds React Fast Refresh code to each component at build time, so it makes sense that this is still happening even with the index.tsx bit commented out. 

Planning to make that "fast refresh" -> "normal HMR" change tonight!

**Comment by FredKSchott** [comment]
Change made here: 7205a03c91c1a2b2b6a406405d4b0906b954358c

When it's ready for general use, we'll add it back to app-scripts-react. Until then, you can opt-in today by adding the plugin to your project-level snowpack config file
