### ISSUE TITLE
react-error-overlay for react-* templates

### ISSUE THREAD

**Issue by popuguytheparrot** [pikapkg/create-snowpack-app#89]
Hi.

I would like to see react-error-overlay during development. It will increase DX and make convenient migration from CRA

**Comment by FredKSchott** [comment]
+1, we've been doing some work on the server-side to support this, lets keep the discussion going over there: https://github.com/pikapkg/esm-hmr/issues/3

The two things to support here are (both in the HMR client):
- there was a server error reported to the client
- there was a runtime error (caught in our HMR client via `window.addEventListener('error', ...`).
