### ISSUE TITLE
Request for a Snowpack 2 + Svelte + Routify template.

### ISSUE THREAD

**Issue by karanganesan** [pikapkg/create-snowpack-app#9]
based on

https://twitter.com/johanalkstal/status/1257789784690491408

**Comment by FredKSchott** [comment]
Happy to kick this off: 

- how does Routify work? 
- Does it read your file system as a part of some build/bundle step? 
- However it detects your file system roots, how can we recreate that as a build script plugin? 

I'm happy to answer that last question if someone can shed some light on how Routify works.

**Comment by karanganesan** [comment]
cc @jakobrosenberg

cross posted the issue on Routify too https://github.com/sveltech/routify/issues/176

**Comment by karanganesan** [comment]
@FredKSchott <-> @jakobrosenberg

https://github.com/sveltech/routify/issues/176#issuecomment-624710120

**Comment by jakobrosenberg** [comment]
Hi @FredKSchott 

Routify itself is very simple from a build perspective. It scans your pages folder and outputs a routes.js with all your route information. I haven't had time to try Snowpack yet, but it's at the top of my list. As such this conversation might be more productive after I've had time to try it out - unless someone else is willing to try porting the current starter template and sharing the experience.

**Comment by FredKSchott** [comment]
NIce! Yea, this seems like a more complex integration since it needs to understand your file tree (most of our builds right now are single-file input->output). But, would love to use this as framework for supporting a more complex plugin like this.

i'm fully focused on getting v2.0.0 released this week, so no rush on my end. I'll ping this thread next week tho, happy to help where I can.

**Comment by FredKSchott** [comment]
Closing since I haven't seen any activity, but happy to reopen if this is something anyone is still interested in pursuing

**Comment by jakobrosenberg** [comment]
I'm trying out Snowpack for our upcoming framework, Roxi. Very excited! Is it possible to run Snowpack programmatically?

I have found references to ``import { install } from 'snowpack'``, but I haven't found any usage examples and the `install` variable seems undefined.

**Comment by jakobrosenberg** [comment]
Currently handling it like this:
```javascript
  process.argv.push('--config', '_roxi/snowpack.config.js')
  require('snowpack/dist-node/index.bin')
```
@FredKSchott is it possible to import absolute paths with Snowpack?

**Comment by FredKSchott** [comment]
It's on our roadmap, would love some help if you're interested in contributing!

https://github.com/pikapkg/snowpack/issues/312

re: importing absolute paths, I don't think that's supported in your application code. The closest thing we have is https://www.snowpack.dev/#project-relative-imports

**Comment by jakobrosenberg** [comment]
@FredKSchott I would love to contribute. Maybe when I get a little more familiar with Snowpack.

I tried mapping the absolute paths to relative paths, but had no luck using `mount`. Then I tried transforming absolute paths to relative paths imports using `script`, but scripts don't seem to support inline code. Lastly I tried a quick inline `plugin`, but learned that plugins have to be strings.

A) Is it possible to transform files directly in `snowpack.config.js`?

B) Is it possible to alias a mount? Roxi has a `roxi` package and Roxi projects have a `roxi` folder in the root containing configs and generated runtime code. Optimally I would be able to alias the local `roxi`folder as `runtime` or similar.

**Comment by FredKSchott** [comment]
@jakobrosenberg you should be able to this:

```js
"scripts": {
  // Example 1: mount "./roxy" folder to "/roxy/*" URLs
  "mount:roxi": "mount roxi"
  // Example 2: mount "./roxy" folder to "/runtime/*" URLs
  "mount:roxi": "mount roxi --to /runtime"
}
```

**Comment by FredKSchott** [comment]
Right now we don't support objects/functions in your "plugins" array, but we do support relative paths to import a plugin:

```
"plugins": ["./my-custom-plugin.js"]
```

**Comment by jakobrosenberg** [comment]
@FredKSchott sorry, I just realized I could have explained B better. If I have both a roxi folder and a roxi package and I mount `roxi` to `runtime`, the roxi package is no longer available.

At the moment I'm handling it by prefixing the roxi folder as `_roxi`.
