### ISSUE TITLE
Missing "csa-template" keyword error

### ISSUE THREAD

**Issue by miljan-aleksic** [pikapkg/create-snowpack-app#96]
Hi,

following the documentation I runned `npx create-snowpack-app new-dir --template vue` and got the following result.

```
- Using template vue
- Creating a new project in /Volumes/.../new-dir

[ERROR] Template is not properly marked as a CSA template (Missing "csa-template" keyword in package.json).
[ERROR] Cannot continue safely. Exiting...
```

I tried blank and react template with same results.

**Comment by jihchi** [comment]
This works for me:

```js
npx create-snowpack-app new-dir --template @snowpack/app-template-vue
```

**Comment by eliamartani** [comment]
> Hi,
> 
> following the documentation I runned `npx create-snowpack-app new-dir --template vue` and got the following result.
> 
> ```
> - Using template vue
> - Creating a new project in /Volumes/.../new-dir
> 
> [ERROR] Template is not properly marked as a CSA template (Missing "csa-template" keyword in package.json).
> [ERROR] Cannot continue safely. Exiting...
> ```
> 
> I tried blank and react template with same results.

You're missing `@snowpack/app-template-` before `vue`.

**Comment by miljan-aleksic** [comment]
Thanks, it's confusing that the error is about a template missconfiguration rather than unexistent template. It clearly states 'Using template vue' and continues forward.

**Comment by FredKSchott** [comment]
Yup, "Using template vue" feels like it's telling you that the package is fine.

We should improve that `missing "csa-template"` error to say something like "this isn't actually a CSA template, check the name to make sure you're using the correct package name".

If anyone is interested in tackling in a PR, I'd love to merge this improvement!

**Comment by stramel** [comment]
I will improve this tomorrow. I noticed this when looking into another issue.
